---
title: "Data Visualization"
author: "Zixi Liu"
date: "4/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# library(ndjson)
# business <- stream_in("business.json")
# names(business)
# str(business)
# 
# checkin <- stream_in("checkin.json")
# names(checkin)
# str(checkin)
# 
# tip <- stream_in("tip.json")
# names(tip)
# str(tip)
# 
# user <- stream_in("user.json")
# names(user)
# str(user)
# 
# library(rjson)
# path <- "review.json"
# c <- file(path, "r")
# l <- readLines(c, 1000)
# json <- lapply(X=l, fromJSON)
# review <- data.frame(matrix(unlist(json), nrow=1000, byrow=TRUE))
# names(review) <- c("review_id", "user_id", "business_id", "stars", "useful", "funny", "cool", "text", "date")
# str(review)
# 
# # Save data into RData
# save(business, checkin, tip, user, review, file = "yelpdata.RData")
# 
# saveRDS(business, file="business.RDS")
# saveRDS(checkin, file="checkin.RDS")
# saveRDS(review, file="review.RDS")
# saveRDS(tip, file="tip.RDS")
# saveRDS(user, file="user.RDS")


 
#Discover you Data what is look like?
library(dplyr) #data manipulation
library(ggplot2) #visualizations
library(gridExtra) #viewing multiple plots together
#install.packages("tidytext")
library(tidytext) #text mining

business <- readRDS("business.RDS")
str(business)
review <- readRDS("review.RDS")
str(review)

head(business)
head(review)
length(unique(business$business_id))
length(unique(tip$business_id))
length(unique(review$business_id))

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
